//
//  MoviesData.swift
//  Movies App
//
//  Created by Moy Macías on 02/05/22.
//

import Foundation

var moviesData: [Movie] = [
  Movie(id: 0, title: "Attack on Titan",  price: 18.85, author: "J. R. R. Tolkien",  genre: ["fantasy", "Action"], description: "The Fellowship of the Ring is the first of three volumes in The Lord of the Rings, an epic set in the fictional world of Middle-earth. The Lord of the Rings is an entity named Sauron, the Dark Lord, who long ago lost the One Ring that contains much of his power. His overriding desire is to reclaim the Ring and use it to enslave all of Middle-earth.", isAvailable: false, imageName: "aot"),
  Movie(id: 1, title: "Avengers End Game", price: 11.99, author: "J. R. R. Tolkien",  genre: ["fantasy", "Action"], description: "The Fellowship was scattered. Some were bracing hopelessly for war against the ancient evil of Sauron. Some were contending with the treachery of the wizard Saruman. Only Frodo and Sam were left to take the accursed Ring of Power to be destroyed in Mordor–the dark Kingdom where Sauron was supreme. Their guide was Gollum, deceitful and lust-filled, slave to the corruption of the Ring.", isAvailable: false, imageName: "avengers"),
  Movie(id: 2, title: "Deamon Slayer", price: 19.99, author: "Yuval Noah Harari",  genre: ["fantasy", "Action"], description: "Yuval Noah Harari envisions a near future in which we face a new set of challenges. Homo Deus explores the projects, dreams and nightmares that will shape the twenty-first century and beyond – from overcoming death to creating artificial life.", isAvailable: false, imageName: "deamon"),
  Movie(id: 3,  title: "Doctor Strange", price: 16.15, author: "Timothy Ferriss", genre: ["fantasy", "Action"], description: "Forget the old concept of retirement and the rest of the deferred-life plan - there is no need to wait and every reason not to, especially in unpredictable economic times. Whether your dream is escaping the rat race, experiencing high-end world travel, earning a monthly five-figure income with zero management, or just living more and working less, this book is the blueprint.", isAvailable: false, imageName: "doctorStrange"),
  Movie(id: 4, title: "Game of Thrones", price: 12.25, author: "Viktor E. Frankl",  genre:["fantasy", "Action"], description: "Psychiatrist Viktor Frankl's memoir has riveted generations of readers with its descriptions of life in Nazi death camps and its lessons for spiritual survival. Between 1942 and 1945 Frankl labored in four different camps, including Auschwitz, while his parents, brother, and pregnant wife perished.", isAvailable: false, imageName: "got"),
  Movie(id: 5, title: "Jujutsu Kaisen", price: 10.99, author: "Homer",  genre: ["fantasy", "Action"], description: "After enduring the Trojan War, Odysseus begins the treacherous journey home to Ithaca. On the way, he faces ravenous monsters and vengeful gods. But the real battle awaits, as his kingdom is under siege by unruly suitors vying for his wife’s hand—and his son’s head. To reclaim his throne and save his family, Odysseus must rely on his wits…and help from the unpredictable gods.", isAvailable: false, imageName: "jujutsu"),
  Movie(id: 6, title: "Lord of the Rings", price: 22.99, author: "Stuart J. Rossell", genre: ["fantasy", "Action"],  description: "The long-anticipated revision of this best-selling text offers the most comprehensive, up-to-date introduction to the theory and practice of artificial intelligence.", isAvailable: false, imageName: "lotr"),
  Movie(id: 7, title: "Peaky blionders", price: 17.85, author: "Ed Catmull", genre: ["fantasy", "Action"], description: "This is the story behind the company that changed animation forever. Here, the founder of Pixar reveals the ideas and techniques that have made Pixar one of the most widely admired creative businesses, and one of the most profitable.", isAvailable: false, imageName: "peaky")
]
